# permissions for end users to view annotatedobjects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: annotatedobject-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: epha
    app.kubernetes.io/part-of: epha
    app.kubernetes.io/managed-by: kustomize
  name: annotatedobject-viewer-role
rules:
  - apiGroups:
      - epha.avyr.io
    resources:
      - annotatedobjects
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - epha.avyr.io
    resources:
      - annotatedobjects/status
    verbs:
      - get
